"""The generator: the use-case file rendered into what the harness and the bridge read.

Pure: the declaration and the hand-written harness settings in, three texts out.

- The harness configuration: the settings copied whole, comments and all, then
  the part this module owns — what each surface may hold, the tool server
  entries with their include lists, and the hook that reports every turn.
  The GitHub server is an entry the harness starts itself, signed in as a
  read-only GitHub App and started with `--read-only`.
- The cron job set: one managed job per enabled schedule use case.
- The bridge's allowlists: one entry per machine client of a server in use.

A dormant use case renders nothing, and neither does a tool server only dormant
use cases name. Every file is written whole and opens with the generated line;
lares regenerates and diffs them in pre-commit, so a hand edit fails there.

The surfaces follow how the harness resolves them. An explicit platform list
that names no tool server hands the platform every server, so an empty one is
the `no_mcp` sentinel. A list for Discord or cron starts with the platform's own
composite, or the chat would lose memory and skills; an explicit Discord list
also switches on the harness's `discord` toolset, which the settings keep
disabled. The API server gets no composite: an event run reads, nothing else.
The Jobs API takes no list per job, so every managed cron job sees the cron
surface, which holds every read server in use, the memory servers the schedule
use cases name, and never a writing one; the loader keeps a memory off a
shared surface any of its use cases would see without keeping one.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, override

import yaml

from .cron_jobs import CronJob, dump_cron_jobs, job_name
from .hermes import language_name
from .hooks import MODEL_CALL, TURN_ENDED
from .receiver import HOOK_PATH
from .use_cases import (
    BridgeServer,
    GitHubServer,
    ScheduleTrigger,
    ToolAccess,
    ToolServer,
    UseCase,
    UseCaseFile,
    load_use_case_file,
)

GENERATED_LINE = "# generated by `task agents:create-harness-config`, do not edit"

# The harness configuration keys this module owns; the settings may not carry them.
RENDERED_KEYS = ("platform_toolsets", "hooks", "mcp_servers")

# The bridge reads its allowlists from this variable, as JSON.
CLIENT_TOOLS_VARIABLE = "MCP_AUTH_CLIENT_TOOLS"

_HOOK_NAME = "lares-agent-trigger"
_HOOK_TIMEOUT_SECONDS = 10
_NO_TOOL_SERVER = "no_mcp"


@dataclass(frozen=True)
class Rendering:
    """The three rendered files, as text."""

    hermes_config: str
    cron_jobs: str
    client_tools: str


class _Dumper(yaml.SafeDumper):
    """Block style with indented sequences, the way the repository writes YAML."""

    @override
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        super().increase_indent(flow, False)


def _dump(data: Any) -> str:
    return yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)


def render(declared: UseCaseFile, settings: str) -> Rendering:
    """Render the declaration; ``settings`` is the text of the hand-written settings file."""
    _check_settings(settings)
    enabled = [use_case for use_case in declared.use_cases.values() if use_case.is_enabled]
    in_use = _servers_named(declared, enabled)

    generated = {
        "platform_toolsets": _platform_toolsets(declared, enabled),
        "hooks": _hooks(declared),
        "mcp_servers": _mcp_servers(in_use),
    }
    hermes_config = (
        f"{GENERATED_LINE}\n"
        "# The hand-written settings.yaml first, then the part rendered from use-cases.yaml.\n"
        "\n"
        f"{settings.rstrip()}\n"
        "\n"
        "# Rendered from use-cases.yaml: what each surface may hold, the tool servers,\n"
        "# and the hook that reports every finished turn.\n"
        f"{_dump(generated)}"
    )
    jobs = [_cron_job(use_case) for use_case in enabled if use_case.is_schedule]
    cron_jobs = (
        f"{GENERATED_LINE}\n"
        "# The cron jobs the harness runs, one per enabled schedule use case.\n"
        f"{_dump(dump_cron_jobs(jobs))}"
    )
    allowlists = {
        server.client: list(server.tools) for server in in_use if isinstance(server, BridgeServer)
    }
    client_tools = (
        f"{GENERATED_LINE}\n"
        "# The tools each machine client of the bridge may see and call.\n"
        f"{CLIENT_TOOLS_VARIABLE}={json.dumps(allowlists, ensure_ascii=False)}\n"
    )
    return Rendering(hermes_config=hermes_config, cron_jobs=cron_jobs, client_tools=client_tools)


def _check_settings(settings: str) -> None:
    try:
        parsed = yaml.safe_load(settings)
    except yaml.YAMLError as exc:
        raise ValueError(f"is not valid YAML ({exc})") from exc
    if not isinstance(parsed, dict):
        raise ValueError("must be a mapping of harness settings")
    for key in RENDERED_KEYS:
        if key in parsed:
            raise ValueError(f"`{key}` is rendered from the use-case file; remove it here")


def _servers_named(
    declared: UseCaseFile, use_cases: Iterable[UseCase], access: ToolAccess | None = None
) -> list[ToolServer]:
    """The servers these use cases name, once each and in file order, optionally of one access."""
    named = {name for use_case in use_cases for name in use_case.tools}
    return [
        server
        for name, server in declared.tool_servers.items()
        if name in named and (access is None or server.access == access)
    ]


def _cron_servers(declared: UseCaseFile, enabled: Sequence[UseCase]) -> list[ToolServer]:
    """Every read server in use and the memory servers schedule use cases name, in file order."""
    schedules = [use_case for use_case in enabled if use_case.is_schedule]
    held = {
        *(server.name for server in _servers_named(declared, enabled, access="read")),
        *(server.name for server in _servers_named(declared, schedules, access="memory")),
    }
    return [server for name, server in declared.tool_servers.items() if name in held]


def _surface(composite: str | None, servers: Sequence[ToolServer]) -> list[str]:
    head = [composite] if composite is not None else []
    return [*head, *([server.name for server in servers] or [_NO_TOOL_SERVER])]


def _platform_toolsets(declared: UseCaseFile, enabled: Sequence[UseCase]) -> dict[str, list[str]]:
    chat = [use_case for use_case in enabled if use_case.is_chat]
    events = [use_case for use_case in enabled if use_case.event_trigger is not None]
    return {
        "discord": _surface("hermes-discord", _servers_named(declared, chat)),
        "api_server": _surface(None, _servers_named(declared, events)),
        "cron": _surface("hermes-cron", _cron_servers(declared, enabled)),
    }


def _hooks(declared: UseCaseFile) -> dict[str, Any]:
    hook = declared.ledger_hook
    return {
        "outbound": [
            {
                "name": _HOOK_NAME,
                "url": f"{hook.trigger_url.rstrip('/')}{HOOK_PATH}",
                "events": [MODEL_CALL, TURN_ENDED],
                "secret_env": hook.secret_env,
                "timeout": _HOOK_TIMEOUT_SECONDS,
            }
        ]
    }


def _mcp_servers(in_use: Sequence[ToolServer]) -> dict[str, Any]:
    return {
        server.name: _bridge_entry(server)
        if isinstance(server, BridgeServer)
        else _github_entry(server)
        for server in in_use
    }


def _bridge_entry(server: BridgeServer) -> dict[str, Any]:
    return {
        "url": server.url,
        "headers": {"Authorization": f"Bearer ${{env:{server.key_env}}}"},
        "timeout": server.timeout_seconds,
        "tools": {"include": list(server.tools)},
    }


def _github_entry(server: GitHubServer) -> dict[str, Any]:
    return {
        "command": server.command,
        "args": ["stdio", "--read-only", f"--toolsets={','.join(server.toolsets)}"],
        # The server mints and renews the App's installation tokens itself.
        "env": {
            "GITHUB_APP_ID": str(server.app_id),
            "GITHUB_APP_INSTALLATION_ID": str(server.installation_id),
            "GITHUB_APP_PRIVATE_KEY_PATH": server.private_key_file,
        },
        "timeout": server.timeout_seconds,
        "tools": {
            "include": list(server.tools),
            # Its prompts walk the model towards writes it does not hold; its
            # resources repeat what the read tools return.
            "resources": False,
            "prompts": False,
        },
    }


def _cron_job(use_case: UseCase) -> CronJob:
    trigger = use_case.trigger
    assert isinstance(trigger, ScheduleTrigger)
    # The loader refuses a schedule use case that names no skill.
    assert use_case.skill is not None
    budget = use_case.budget
    return CronJob(
        name=job_name(use_case),
        schedule=trigger.cron,
        skills=(use_case.skill,),
        prompt=(
            f"Answer in {language_name(use_case.language)}. "
            f"Stay within {budget.tool_calls} tool calls and {budget.minutes} minutes."
        ),
        # The trigger delivers; the harness keeps the output to itself.
        deliver="local",
    )


def main(argv: Sequence[str] | None = None) -> int:
    """`lares-agent-trigger generate`: render the declaration and write the three files."""
    parser = argparse.ArgumentParser(
        prog="lares-agent-trigger generate",
        description="Render the use-case file into the harness configuration, "
        "the cron job set and the bridge's allowlists.",
    )
    parser.add_argument("--use-cases", type=Path, required=True)
    parser.add_argument("--settings", type=Path, required=True)
    parser.add_argument("--hermes-config", type=Path, required=True)
    parser.add_argument("--cron-jobs", type=Path, required=True)
    parser.add_argument("--client-tools", type=Path, required=True)
    args = parser.parse_args(argv)

    try:
        declared = load_use_case_file(args.use_cases)
        try:
            settings = args.settings.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValueError(f"{args.settings}: cannot be read ({exc})") from exc
        try:
            rendered = render(declared, settings)
        except ValueError as exc:
            raise ValueError(f"{args.settings}: {exc}") from exc
    except ValueError as exc:
        print(f"generate: {exc}", file=sys.stderr)
        return 1

    for path, text in (
        (args.hermes_config, rendered.hermes_config),
        (args.cron_jobs, rendered.cron_jobs),
        (args.client_tools, rendered.client_tools),
    ):
        try:
            path.write_text(text, encoding="utf-8")
        except OSError as exc:
            print(f"generate: {path}: cannot be written ({exc})", file=sys.stderr)
            return 1
    return 0
